/*----- constants -----*/
//None

/*----- state variables -----*/

// creating an array to keep track of the computer sequence of tile clicks
let sequence = [];

// creating an array to keep track of the player sequence of tile clicks
let playerSequence = [];

//set level to 0 since the player has not played any levels yet
let level = 0;

/*----- cached elements  -----*/

const startButton = document.querySelector('#start-button');
const message = document.querySelector('#message');
const levelMessage = document.querySelector('h2');
const board = document.querySelector('#board');

/*----- event listeners -----*/
//Add even listerner to start button so that it starts the game by unning clickStart function
startButton.addEventListener('click', clickStart);

//Add event listener to the tiles on the board 
board.addEventListener('click', handleClick)


/*----- functions -----*/

//when start button is clicked, hide this button
// If the order does not match, the game resets AND THE MESSAGE WILL SHOW THAT THE GAME IS OVER
// Run the original stateof he game
function clickStart() {
  startButton.classList.add('hidden');
  message.classList.remove('hidden');
  nextRound();
}

// compare the order in which the player taps the buttons to the order of the sequence generated by the computer
function resetGame() {
  sequence = [];
  playerSequence = [];
  level = 0;
  startButton.classList.remove('hidden');
  levelMessage.textContent = '';
  message.classList.add('hidden');
  board.classList.add('unclickable');
}

// remove the unclickable class from the board
//update message to show it's player turn and the number of taps the player need to make
function playerTurn(level) {
  board.classList.remove('unclickable');
  message.textContent = `Your turn: ${level} Tap${level > 1 ? 's' : ''}`;
}


// Activate the tiles on the screen
//Select appropriate audio element and play it
function activateTile(color) {
  const tile = document.querySelector(`[data-tile='${color}']`);
  const sound = document.querySelector(`[data-sound='${color}']`);

  tile.classList.add('activated');
  sound.play();

  setTimeout(() => {
    tile.classList.remove('activated');
  }, 300);
}

// Add delay between each button press
function playRound(nextSequence) {
  nextSequence.forEach((color, index) => {
    setTimeout(() => {
      activateTile(color);
    }, (index + 1) * 600);
  });
}

// pick a random tile and return it
// A tile value is picked that corresponds to the data-tile property in the html
function nextStep() {
  const tiles = ['red', 'green', 'blue', 'yellow'];
  const random = tiles[Math.floor(Math.random() * tiles.length)];
  return random;
}

// increase level by 1, make the board unclickable and show the new level
// create a new sequence by grabing the random return of nextStep function
// Add a delay before playerTurn is run to make sure computer is done with the taps
function nextRound() {
  level += 1;
  board.classList.add('unclickable');
  levelMessage.textContent = `Level ${level} of 35`;

  const nextSequence = [...sequence];
  nextSequence.push(nextStep());
  playRound(nextSequence);

  sequence = [...nextSequence];
  setTimeout(() => {
    playerTurn(level);
  }, level * 600 + 1000);
}

// pushes the tile value to the playerSequence array and stores its index in the index variable
// Play the corresponding sound for the button that is played
// Show either game over or congrats message on the screen
// Show 'your turn' message
// Reset the Sequence array and call the nextRound() function after one second
// Detemine if all levels are played and show a congrats message where the player wins the game after 35 rounds
function handleClick(event) {
  const {tile} = event.target.dataset;
  console.log(tile)

  if (tile) {
    const index = playerSequence.push(tile) - 1;
    const sound = document.querySelector(`[data-sound='${tile}']`);
    sound.play();

    if (playerSequence[index] !== sequence[index]) {
      resetGame('Oops! Game over, you pressed the wrong tile');
      return;
    }

    if (playerSequence.length === sequence.length) {
      if (playerSequence.length === 35) {
        resetGame('Congrats! You completed all the levels');
        return;
      }

      playerSequence = [];
      setTimeout(() => {
        nextRound();
      }, 1000);
      return;
    }
  }
}

